#!/usr/bin/env bash
#
# Prepares the container for `dart test`, then execs the given command.
set -euo pipefail

: "${DSN:=postgres}"
: "${DB_USER:=odbc_test}"
: "${DB_PASSWORD:=odbc_test}"
: "${DB_NAME:=odbc_test}"

# The tests read configuration from a '.env' file via package:dotenv. Writing
# the file here means the container works without relying on dotenv's
# platform-environment behaviour.
#
# The file is generated, so it carries a marker line. Two rules follow from it:
#
#   - A .env WITHOUT the marker was hand-written by a contributor (the source
#     tree is bind-mounted, so their real file is visible here). Never touch it.
#   - A generated .env for a DIFFERENT engine is stale -- switching between
#     TEST_DB=postgres and TEST_DB=mariadb must not silently reuse the previous
#     DSN, which would point the tests at the wrong database.
GENERATED_MARKER='# generated by docker/entrypoint.sh'

if [ ! -f .env ]; then
  write_env=yes
elif ! head -1 .env | grep -qF "$GENERATED_MARKER"; then
  echo "[entrypoint] keeping hand-written .env"
  write_env=no
elif grep -qF "DSN='${DSN}'" .env; then
  write_env=no
else
  echo "[entrypoint] .env was generated for another engine; regenerating"
  write_env=yes
fi

if [ "$write_env" = yes ]; then
  echo "[entrypoint] writing .env for DSN='${DSN}'"
  cat > .env <<EOF
${GENERATED_MARKER}
DSN='${DSN}'
USERNAME='${DB_USER}'
PASSWORD='${DB_PASSWORD}'
DATABASE='${DB_NAME}'
EOF
fi

# `dart pub get` exits non-zero at the repo root because it recurses into
# example/, a Flutter app that needs the Flutter SDK. It still writes a valid
# package_config.json, so tolerate that specific failure but verify the artifact
# that actually matters -- otherwise a real resolution failure would be masked.
dart pub get >/dev/null 2>&1 \
  || echo "[entrypoint] note: pub get warned (example/ needs Flutter); continuing"

if [ ! -f .dart_tool/package_config.json ]; then
  echo "[entrypoint] ERROR: dependency resolution genuinely failed" >&2
  dart pub get || true
  exit 1
fi

exec "$@"
